image: docker:latest

services:
  - docker:dind

stages:
  - build_push

variables:
  DOCKER_DRIVER: overlay2

build-and-push:
  stage: build_push
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - docker build -t $DOCKER_USERNAME/server:$CI_COMMIT_SHORT_SHA/server:latest ./app/server
    - docker build -t $DOCKER_USERNAME/client:$CI_COMMIT_SHORT_SHA/client:latest ./app/client

    - docker push $DOCKER_USERNAME/server:latest
    - docker push $DOCKER_USERNAME/client:latest