image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2

build-server:
  stage: build
  script:
    - docker build -t $DOCKER_USERNAME/server:latest ./app/server

build-client:
  stage: build
  script:
    - docker build -t $DOCKER_USERNAME/client:latest ./app/client

push-images:
  stage: push
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_USERNAME/server:latest
    - docker push $DOCKER_USERNAME/client:latest